ALTER TABLE clientes DROP COLUMN IF EXISTS direc1;
ALTER TABLE clientes DROP COLUMN IF EXISTS telefonos;
ALTER TABLE clientes DROP COLUMN IF EXISTS fax;
ALTER TABLE clientes DROP COLUMN IF EXISTS desc_glob;
