BEGIN;

CREATE TABLE IF NOT EXISTS prov (
    co_prov  VARCHAR(30)   NOT NULL PRIMARY KEY,
    prov_des VARCHAR(255)  NOT NULL
);

ALTER TABLE art ADD COLUMN IF NOT EXISTS co_prov VARCHAR(30);

ALTER TABLE art
    DROP CONSTRAINT IF EXISTS fk_art_prov;

ALTER TABLE art
    ADD CONSTRAINT fk_art_prov
    FOREIGN KEY (co_prov) REFERENCES prov(co_prov) ON DELETE SET NULL;

COMMIT;
