BEGIN;

CREATE TABLE IF NOT EXISTS prov (
    co_prov  VARCHAR(30)   NOT NULL PRIMARY KEY,
    prov_des VARCHAR(255)  NOT NULL
);

ALTER TABLE clientes ADD COLUMN IF NOT EXISTS co_prov VARCHAR(30);

ALTER TABLE clientes
    DROP CONSTRAINT IF EXISTS fk_clientes_prov;

ALTER TABLE clientes
    ADD CONSTRAINT fk_clientes_prov
    FOREIGN KEY (co_prov) REFERENCES prov(co_prov) ON DELETE SET NULL;

COMMIT;
