ALTER TABLE desc_ptc
    DROP COLUMN IF EXISTS hasta6,
    DROP COLUMN IF EXISTS hasta7,
    DROP COLUMN IF EXISTS hasta8,
    DROP COLUMN IF EXISTS hasta9,
    DROP COLUMN IF EXISTS hasta10,
    DROP COLUMN IF EXISTS porc6,
    DROP COLUMN IF EXISTS porc7,
    DROP COLUMN IF EXISTS porc8,
    DROP COLUMN IF EXISTS porc9,
    DROP COLUMN IF EXISTS porc10;
