ALTER TABLE clientes ADD COLUMN IF NOT EXISTS direc1 VARCHAR(255);
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS telefonos VARCHAR(255);
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS fax VARCHAR(50);
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS desc_glob NUMERIC(15,2) DEFAULT 0;
