ALTER TABLE desc_ptc
    ADD COLUMN IF NOT EXISTS hasta6  DECIMAL(18,5) DEFAULT 0,
    ADD COLUMN IF NOT EXISTS hasta7  DECIMAL(18,5) DEFAULT 0,
    ADD COLUMN IF NOT EXISTS hasta8  DECIMAL(18,5) DEFAULT 0,
    ADD COLUMN IF NOT EXISTS hasta9  DECIMAL(18,5) DEFAULT 0,
    ADD COLUMN IF NOT EXISTS hasta10 DECIMAL(18,5) DEFAULT 0,
    ADD COLUMN IF NOT EXISTS porc6   DECIMAL(18,5) DEFAULT 0,
    ADD COLUMN IF NOT EXISTS porc7   DECIMAL(18,5) DEFAULT 0,
    ADD COLUMN IF NOT EXISTS porc8   DECIMAL(18,5) DEFAULT 0,
    ADD COLUMN IF NOT EXISTS porc9   DECIMAL(18,5) DEFAULT 0,
    ADD COLUMN IF NOT EXISTS porc10  DECIMAL(18,5) DEFAULT 0;
